spring.application.name=zepto-backend
server.port=5050

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/zepto}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 

security.secret.password=skshjdjjsvjsnksnxksAKjfjdkjcdgjmjfjkfvfjbxvfdxskjjkgvgc4r657fcgdxygdr




